# SPDX-FileCopyrightText: 2026 Isac Pasianotto <isac.pasianotto@phd.units.it>
# SPDX-FileCopyrightText: 2026 Niccolo Tosato <niccolo.tosato@phd.units.it>
#
# SPDX-License-Identifier: CC-BY-4.0

[agent]
  interval = "30s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  precision = "1ms"
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "5s"

[[outputs.influxdb]]
  urls = ["https://timeseriesdb.dev.rd.areasciencepark.it"]
  database = "telegraf"
  skip_database_creation = true
  timeout = "120s"
  insecure_skip_verify = true
  content_encoding = "identity"

[[inputs.exec]]
  interval = "30s"
  timeout  = "120s"
  commands = ["bash /etc/telegraf/pdu_metrics.sh"]
  data_format = "influx"
