# SPDX-FileCopyrightText: 2026 Isac Pasianotto <isac.pasianotto@phd.units.it>
# SPDX-FileCopyrightText: 2026 Niccolo Tosato <niccolo.tosato@phd.units.it>
#
# SPDX-License-Identifier: CC-BY-4.0

---

debug: false

container_image: "docker.io/pasianeight/telegraf-monitoring"
container_name: "telegraf-quadlet"
