# SPDX-FileCopyrightText: 2026 Isac Pasianotto <isac.pasianotto@phd.units.it>
# SPDX-FileCopyrightText: 2026 Niccolo Tosato <niccolo.tosato@phd.units.it>
#
# SPDX-License-Identifier: CC-BY-4.0

---
apiVersion: v1
kind: Secret
metadata:
  name: energymeter-secret
  namespace: temporaldb
type: Opaque
data:
  ENERGYMETER_USERNAME: omitted
  ENERGYMETER_PASSWORD: omitted
