# SPDX-FileCopyrightText: 2026 Isac Pasianotto <isac.pasianotto@phd.units.it>
# SPDX-FileCopyrightText: 2026 Niccolo Tosato <niccolo.tosato@phd.units.it>
#
# SPDX-License-Identifier: CC-BY-4.0

---
apiVersion: v1
kind: Secret
metadata:
  name: demo-db-credentials
  namespace: temporaldb
type: kubernetes.io/basic-auth
data:
  username: ${PG_USERNAME}
  password: ${PG_PASSWORD}
