apiVersion: v1
kind: Service
metadata:
  name: demo-db-external
  namespace: temporaldb
  annotations:
    metallb.universe.tf/address-pool: ${METALLB_POOL}
spec:
  type: LoadBalancer
  loadBalancerIP: ${METALLB_IP}
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30432
  selector:
    cnpg.io/cluster: demo-db
    role: primary
