; SPDX-FileCopyrightText: 2026 Isac Pasianotto <isac.pasianotto@phd.units.it>
; SPDX-FileCopyrightText: 2026 Niccolo Tosato <niccolo.tosato@phd.units.it>
;
; SPDX-License-Identifier: CC-BY-4.0

IOR START
    #  -----------  Backend / target ------------
    # api overridden by CLI with -a <POSIX|MPIIO|HDF5>
    # api=POSIX
    testFile=/orfeo/cephfs/fast/area/ipasia00/iorfiles/ior_rand_4k

    # MPI number of tasks, overridden by CLI with -N <numTasks>
    # numTasks=1

    # -----------  Repetitions / pacing ------------
    repetitions=1
    interTestDelay=1

    # -----------  Operation type ------------
    # randomOffset=0 means sequential access, 1 means random access
    readFile=0
    writeFile=1
    randomOffset=1

    multiFile=0

    # 1 = each process write on its own file, 0 = all processes write on the same file
    filePerProc=1
    # filePerProc=0

    # -----------  I/O sizes ------------
    # transferSize: size of each I/O operation
    transferSize=4k

    # blockSize: total bytes written per rank (must be >> throughput * duration)
    # Set very large so the test stops by time (60s), not by "finished file size"
    blockSize=20g


    # -----------  Time-bounded run ------------
    # maxTimeDuration: stop the test after this many seconds (overrides blockSize)
    # !!! is in minutes
    maxTimeDuration=3

    # !!! is in seconds;  default is 0 -> disable
    deadlineForStonewalling=180

    # cacheing
    fsync=1
    fsyncPerWrite=0
    useO_DIRECT=1

    # ----------- General options ------------
    # uniqueDir=0
    useExistingTestFile=0
    keepFile=0
    keepFileWithError=0

    # mpi
    # collective=1

    checkWrite=0
    checkRead=0
    setTimeStampSignature=0
    singleXferAttempt=0

    outlierThreshold=0
    verbose=0
RUN
IOR STOP
