apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: polaris-dply-s3-credentials
  namespace: polaris-tsdb-catalog
data:
  access-key: <YOUR_ACCESS_KEY_BASE64_ENCODED>                      # <-- TODO: replace this
  secret-key: <YOUR_SECRET_KEY_BASE64_ENCODED>                      # <-- TODO: replace this
---
apiVersion: v1
kind: Secret
metadata:
  name: polaris-credentials
  namespace: polaris-tsdb-catalog
type: Opaque
stringData:
  # must be equal to `POLARIS_BOOTSTRAP_CREDENTIALS`
  client-id: polaris_admin
  client-secret: <YOUR_POLARIS_ADMIN_PASSWORD>                                  # <-- TODO: replace this
  credential: polaris_admin:<YOUR_POLARIS_ADMIN_PASSWORD>                       # <-- TODO: replace this
  bootstrapcredentials: POLARIS,polaris_admin,<YOUR_POLARIS_ADMIN_PASSWORD>     # <-- TODO: replace this
