# SPDX-FileCopyrightText: 2026 Isac Pasianotto <isac.pasianotto@phd.units.it>
# SPDX-FileCopyrightText: 2026 Niccolo Tosato <niccolo.tosato@phd.units.it>
#
# SPDX-License-Identifier: CC-BY-4.0

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: polaris-tsdb-catalog
type: Opaque
stringData:
  password: "<YOUR_POSTGRES_PASSWORD>"                                        # <-- TODO: replace this
  user: "polaris"

# --- Optional, needed only if backup is actrive in 04-postgres-cluster.yaml
# ---
# apiVersion: v1
# kind: Secret
# type: Opaque
# metadata:
#   name: cnpg-polaris-backups3
#   namespace: polaris-tsdb-catalog
# data:
#   AWS_ACCESS_KEY_ID: <YOUR_AWS_ACCESS_KEY_ID_BASE64_ENCODED>                  # <-- TODO: replace this
#   AWS_SECRET_ACCESS_KEY: <YOUR_AWS_SECRET_ACCESS_KEY_BASE64_ENCODED>          # <-- TODO: replace this