# SPDX-FileCopyrightText: 2026 Isac Pasianotto <isac.pasianotto@phd.units.it>
# SPDX-FileCopyrightText: 2026 Niccolo Tosato <niccolo.tosato@phd.units.it>
#
# SPDX-License-Identifier: CC-BY-4.0

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: polaris-data
  namespace: polaris-tsdb-catalog
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: rbd-nvme-xfs-replica       # <-- TODO: replace this with the name of your StorageClass
